-- T9: Map visualization of T2 and T3 results

USE WAREHOUSE BIGDATA_MZMB_WH;
USE DATABASE BIGDATA_TAXI_MZMB;

CREATE OR REPLACE TABLE GOLD.T9_QUALITY_BY_ZONE AS
WITH yellow_q AS (
    SELECT PU_LOCATION_ID AS LOCATION_ID, COUNT(*) AS TOTAL_TRIPS,
        SUM(CASE WHEN TRIP_DISTANCE = 0 THEN 1 ELSE 0 END) AS ZERO_DISTANCE,
        SUM(CASE WHEN PICKUP_DATETIME = DROPOFF_DATETIME THEN 1 ELSE 0 END) AS PICKUP_EQUALS_DROPOFF,
        SUM(CASE WHEN DROPOFF_DATETIME < PICKUP_DATETIME THEN 1 ELSE 0 END) AS DROPOFF_BEFORE_PICKUP,
        SUM(CASE WHEN FARE_AMOUNT < 0 THEN 1 ELSE 0 END) AS NEGATIVE_FARE,
        'yellow' AS DATASET
    FROM SILVER.YELLOW_TRIPS
    WHERE PICKUP_YEAR BETWEEN 2012 AND 2026 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
),
green_q AS (
    SELECT PU_LOCATION_ID, COUNT(*),
        SUM(CASE WHEN TRIP_DISTANCE = 0 THEN 1 ELSE 0 END),
        SUM(CASE WHEN PICKUP_DATETIME = DROPOFF_DATETIME THEN 1 ELSE 0 END),
        SUM(CASE WHEN DROPOFF_DATETIME < PICKUP_DATETIME THEN 1 ELSE 0 END),
        SUM(CASE WHEN FARE_AMOUNT < 0 THEN 1 ELSE 0 END),
        'green'
    FROM SILVER.GREEN_TRIPS
    WHERE PICKUP_YEAR BETWEEN 2014 AND 2026 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
),
fhv_q AS (
    SELECT PU_LOCATION_ID, COUNT(*),
        0,
        SUM(CASE WHEN PICKUP_DATETIME = DROPOFF_DATETIME THEN 1 ELSE 0 END),
        SUM(CASE WHEN DROPOFF_DATETIME < PICKUP_DATETIME THEN 1 ELSE 0 END),
        0,
        'fhv'
    FROM SILVER.FHV_TRIPS
    WHERE PICKUP_YEAR BETWEEN 2015 AND 2026 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
),
fhvhv_q AS (
    SELECT PU_LOCATION_ID, COUNT(*),
        SUM(CASE WHEN TRIP_MILES <= 0 THEN 1 ELSE 0 END),
        SUM(CASE WHEN PICKUP_DATETIME = DROPOFF_DATETIME THEN 1 ELSE 0 END),
        SUM(CASE WHEN DROPOFF_DATETIME < PICKUP_DATETIME THEN 1 ELSE 0 END),
        SUM(CASE WHEN BASE_PASSENGER_FARE < 0 THEN 1 ELSE 0 END),
        'fhvhv'
    FROM SILVER.FHVHV_TRIPS
    WHERE PICKUP_YEAR BETWEEN 2019 AND 2026 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
),
combined AS (
    SELECT * FROM yellow_q UNION ALL SELECT * FROM green_q
    UNION ALL SELECT * FROM fhv_q UNION ALL SELECT * FROM fhvhv_q
)
SELECT
    c.*,
    tz.BOROUGH,
    tz.ZONE,
    ROUND((c.ZERO_DISTANCE + c.PICKUP_EQUALS_DROPOFF + c.DROPOFF_BEFORE_PICKUP + c.NEGATIVE_FARE)
        * 100.0 / NULLIF(c.TOTAL_TRIPS, 0), 2) AS TOTAL_ISSUE_PCT
FROM combined c
LEFT JOIN EXTERNAL_DATA.TAXI_ZONE_LOOKUP tz ON c.LOCATION_ID = tz.LOCATION_ID;

CREATE OR REPLACE TABLE GOLD.T9_COVID_BY_ZONE AS
WITH pre AS (
    SELECT PU_LOCATION_ID AS LOCATION_ID, COUNT(*) AS TRIPS_2019
    FROM SILVER.YELLOW_TRIPS_CLEAN WHERE PICKUP_YEAR = 2019 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
),
post AS (
    SELECT PU_LOCATION_ID AS LOCATION_ID, COUNT(*) AS TRIPS_2020
    FROM SILVER.YELLOW_TRIPS_CLEAN WHERE PICKUP_YEAR = 2020 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
)
SELECT
    COALESCE(pre.LOCATION_ID, post.LOCATION_ID) AS LOCATION_ID,
    COALESCE(pre.TRIPS_2019, 0) AS TRIPS_2019,
    COALESCE(post.TRIPS_2020, 0) AS TRIPS_2020,
    ROUND((COALESCE(post.TRIPS_2020, 0) - COALESCE(pre.TRIPS_2019, 0)) * 100.0
        / NULLIF(pre.TRIPS_2019, 0), 2) AS PCT_CHANGE
FROM pre FULL OUTER JOIN post ON pre.LOCATION_ID = post.LOCATION_ID;

CREATE OR REPLACE TABLE GOLD.T9_HOURLY_BY_ZONE AS
WITH hourly AS (
    SELECT PU_LOCATION_ID AS LOCATION_ID, HOUR(PICKUP_DATETIME) AS HR, COUNT(*) AS TRIP_COUNT
    FROM SILVER.YELLOW_TRIPS_CLEAN WHERE PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID, HOUR(PICKUP_DATETIME)
),
peak AS (
    SELECT LOCATION_ID, HR AS PEAK_HOUR, TRIP_COUNT,
        ROW_NUMBER() OVER (PARTITION BY LOCATION_ID ORDER BY TRIP_COUNT DESC) AS RN
    FROM hourly
),
totals AS (
    SELECT LOCATION_ID, SUM(TRIP_COUNT) AS TOTAL_TRIPS,
        SUM(CASE WHEN HR BETWEEN 7 AND 9 THEN TRIP_COUNT ELSE 0 END) AS MORNING_TRIPS,
        SUM(CASE WHEN HR BETWEEN 17 AND 19 THEN TRIP_COUNT ELSE 0 END) AS EVENING_TRIPS,
        SUM(CASE WHEN HR BETWEEN 22 AND 23 OR HR BETWEEN 0 AND 4 THEN TRIP_COUNT ELSE 0 END) AS NIGHT_TRIPS
    FROM hourly GROUP BY LOCATION_ID
)
SELECT t.LOCATION_ID, p.PEAK_HOUR, t.TOTAL_TRIPS,
    ROUND(t.MORNING_TRIPS * 100.0 / t.TOTAL_TRIPS, 2) AS MORNING_PCT,
    ROUND(t.EVENING_TRIPS * 100.0 / t.TOTAL_TRIPS, 2) AS EVENING_PCT,
    ROUND(t.NIGHT_TRIPS * 100.0 / t.TOTAL_TRIPS, 2) AS NIGHT_PCT
FROM totals t JOIN peak p ON t.LOCATION_ID = p.LOCATION_ID AND p.RN = 1;

CREATE OR REPLACE TABLE GOLD.T9_RECOVERY_BY_ZONE AS
WITH pre AS (
    SELECT PU_LOCATION_ID AS LOCATION_ID, COUNT(*) / 12.0 AS AVG_MONTHLY_2019
    FROM SILVER.YELLOW_TRIPS_CLEAN WHERE PICKUP_YEAR = 2019 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
),
post AS (
    SELECT PU_LOCATION_ID AS LOCATION_ID, COUNT(*) / 12.0 AS AVG_MONTHLY_2024
    FROM SILVER.YELLOW_TRIPS_CLEAN WHERE PICKUP_YEAR = 2024 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
)
SELECT
    COALESCE(pre.LOCATION_ID, post.LOCATION_ID) AS LOCATION_ID,
    ROUND(COALESCE(pre.AVG_MONTHLY_2019, 0), 0) AS AVG_MONTHLY_2019,
    ROUND(COALESCE(post.AVG_MONTHLY_2024, 0), 0) AS AVG_MONTHLY_2024,
    ROUND(COALESCE(post.AVG_MONTHLY_2024, 0) * 100.0 / NULLIF(pre.AVG_MONTHLY_2019, 0), 1) AS RECOVERY_PCT
FROM pre FULL OUTER JOIN post ON pre.LOCATION_ID = post.LOCATION_ID;