-- T9: Map visualization support
-- Creates zone-level quality table using T2 quality checks applied per pickup zone
-- Volume data comes from T3_PICKUP_LOCATION_DIST (already exists)
-- Zone geometries come from EXTERNAL_DATA.TAXI_ZONES_GEOM (already exists)

USE WAREHOUSE BIGDATA_MZMB_WH;
USE DATABASE BIGDATA_TAXI_MZMB;

CREATE OR REPLACE TABLE GOLD.T9_QUALITY_BY_ZONE AS
WITH yellow_q AS (
    SELECT PU_LOCATION_ID AS LOCATION_ID, COUNT(*) AS TOTAL_TRIPS,
        SUM(CASE WHEN TRIP_DISTANCE = 0 THEN 1 ELSE 0 END) AS ZERO_DISTANCE,
        SUM(CASE WHEN PICKUP_DATETIME = DROPOFF_DATETIME THEN 1 ELSE 0 END) AS PICKUP_EQUALS_DROPOFF,
        SUM(CASE WHEN DROPOFF_DATETIME < PICKUP_DATETIME THEN 1 ELSE 0 END) AS DROPOFF_BEFORE_PICKUP,
        SUM(CASE WHEN FARE_AMOUNT < 0 THEN 1 ELSE 0 END) AS NEGATIVE_FARE,
        'yellow' AS DATASET
    FROM SILVER.YELLOW_TRIPS
    WHERE PICKUP_YEAR BETWEEN 2012 AND 2026 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
),
green_q AS (
    SELECT PU_LOCATION_ID, COUNT(*),
        SUM(CASE WHEN TRIP_DISTANCE = 0 THEN 1 ELSE 0 END),
        SUM(CASE WHEN PICKUP_DATETIME = DROPOFF_DATETIME THEN 1 ELSE 0 END),
        SUM(CASE WHEN DROPOFF_DATETIME < PICKUP_DATETIME THEN 1 ELSE 0 END),
        SUM(CASE WHEN FARE_AMOUNT < 0 THEN 1 ELSE 0 END),
        'green'
    FROM SILVER.GREEN_TRIPS
    WHERE PICKUP_YEAR BETWEEN 2014 AND 2026 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
),
fhv_q AS (
    SELECT PU_LOCATION_ID, COUNT(*),
        0,
        SUM(CASE WHEN PICKUP_DATETIME = DROPOFF_DATETIME THEN 1 ELSE 0 END),
        SUM(CASE WHEN DROPOFF_DATETIME < PICKUP_DATETIME THEN 1 ELSE 0 END),
        0,
        'fhv'
    FROM SILVER.FHV_TRIPS
    WHERE PICKUP_YEAR BETWEEN 2015 AND 2026 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
),
fhvhv_q AS (
    SELECT PU_LOCATION_ID, COUNT(*),
        SUM(CASE WHEN TRIP_MILES <= 0 THEN 1 ELSE 0 END),
        SUM(CASE WHEN PICKUP_DATETIME = DROPOFF_DATETIME THEN 1 ELSE 0 END),
        SUM(CASE WHEN DROPOFF_DATETIME < PICKUP_DATETIME THEN 1 ELSE 0 END),
        SUM(CASE WHEN BASE_PASSENGER_FARE < 0 THEN 1 ELSE 0 END),
        'fhvhv'
    FROM SILVER.FHVHV_TRIPS
    WHERE PICKUP_YEAR BETWEEN 2019 AND 2026 AND PU_LOCATION_ID IS NOT NULL
    GROUP BY PU_LOCATION_ID
),
combined AS (
    SELECT * FROM yellow_q UNION ALL SELECT * FROM green_q
    UNION ALL SELECT * FROM fhv_q UNION ALL SELECT * FROM fhvhv_q
)
SELECT
    c.*,
    tz.BOROUGH,
    tz.ZONE,
    ROUND((c.ZERO_DISTANCE + c.PICKUP_EQUALS_DROPOFF + c.DROPOFF_BEFORE_PICKUP + c.NEGATIVE_FARE)
        * 100.0 / NULLIF(c.TOTAL_TRIPS, 0), 2) AS TOTAL_ISSUE_PCT
FROM combined c
LEFT JOIN EXTERNAL_DATA.TAXI_ZONE_LOOKUP tz ON c.LOCATION_ID = tz.LOCATION_ID;
