-- T4: Storage format comparison (Snowflake stage exports)
-- Dataset: SILVER.GREEN_TRIPS_CLEAN WHERE PICKUP_YEAR = 2024 (617,885 rows)
-- Python benchmarks (Parquet, CSV, CSV.gz, HDF5) in t4_benchmark.ipynb

USE WAREHOUSE BIGDATA_MZMB_WH;
USE DATABASE BIGDATA_TAXI_MZMB;

CREATE OR REPLACE STAGE GOLD.T4_FORMAT_STAGE;

COPY INTO @GOLD.T4_FORMAT_STAGE/parquet/
FROM (SELECT * FROM SILVER.GREEN_TRIPS_CLEAN WHERE PICKUP_YEAR = 2024)
FILE_FORMAT = (TYPE = 'PARQUET')
HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @GOLD.T4_FORMAT_STAGE/csv/
FROM (SELECT * FROM SILVER.GREEN_TRIPS_CLEAN WHERE PICKUP_YEAR = 2024)
FILE_FORMAT = (TYPE = 'CSV' COMPRESSION = 'NONE' FIELD_OPTIONALLY_ENCLOSED_BY = '"')
HEADER = TRUE OVERWRITE = TRUE;

COPY INTO @GOLD.T4_FORMAT_STAGE/csv_gz/
FROM (SELECT * FROM SILVER.GREEN_TRIPS_CLEAN WHERE PICKUP_YEAR = 2024)
FILE_FORMAT = (TYPE = 'CSV' COMPRESSION = 'GZIP' FIELD_OPTIONALLY_ENCLOSED_BY = '"')
HEADER = TRUE OVERWRITE = TRUE;

LIST @GOLD.T4_FORMAT_STAGE/;

CREATE OR REPLACE FILE FORMAT GOLD.T4_PARQUET_FF TYPE = 'PARQUET';
CREATE OR REPLACE FILE FORMAT GOLD.T4_CSV_FF TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1;
CREATE OR REPLACE FILE FORMAT GOLD.T4_CSV_GZ_FF TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 COMPRESSION = 'GZIP';

SELECT COUNT(*) FROM @GOLD.T4_FORMAT_STAGE/parquet/ (FILE_FORMAT => 'GOLD.T4_PARQUET_FF');
SELECT COUNT(*) FROM @GOLD.T4_FORMAT_STAGE/csv/ (FILE_FORMAT => 'GOLD.T4_CSV_FF');
SELECT COUNT(*) FROM @GOLD.T4_FORMAT_STAGE/csv_gz/ (FILE_FORMAT => 'GOLD.T4_CSV_GZ_FF');
