USE WAREHOUSE BIGDATA_MZMB_WH;
USE DATABASE BIGDATA_TAXI_MZMB;
USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT PARQUET_FF
  TYPE = PARQUET;

CREATE OR REPLACE STAGE YELLOW_RAW_STAGE
  FILE_FORMAT = PARQUET_FF;

CREATE OR REPLACE STAGE GREEN_RAW_STAGE
  FILE_FORMAT = PARQUET_FF;

CREATE OR REPLACE STAGE FHV_RAW_STAGE
  FILE_FORMAT = PARQUET_FF;

CREATE OR REPLACE STAGE FHVHV_RAW_STAGE
  FILE_FORMAT = PARQUET_FF;

LIST @YELLOW_RAW_STAGE;

CREATE OR REPLACE TABLE T0_YELLOW_SCHEMA AS
SELECT
  'yellow' AS dataset,
  column_name,
  type AS column_type,
  nullable,
  expression,
  filenames,
  order_id
FROM TABLE(
  INFER_SCHEMA(
    LOCATION => '@YELLOW_RAW_STAGE',
    FILE_FORMAT => 'PARQUET_FF'
  )
);

LIST @GREEN_RAW_STAGE;

CREATE OR REPLACE TABLE T0_GREEN_SCHEMA AS
SELECT
  'green' AS dataset,
  column_name,
  type AS column_type,
  nullable,
  expression,
  filenames,
  order_id
FROM TABLE(
  INFER_SCHEMA(
    LOCATION => '@GREEN_RAW_STAGE',
    FILE_FORMAT => 'PARQUET_FF'
  )
);

LIST @FHV_RAW_STAGE;

CREATE OR REPLACE TABLE T0_FHV_SCHEMA AS
SELECT
  'fhv' AS dataset,
  column_name,
  type AS column_type,
  nullable,
  expression,
  filenames,
  order_id
FROM TABLE(
  INFER_SCHEMA(
    LOCATION => '@FHV_RAW_STAGE',
    FILE_FORMAT => 'PARQUET_FF'
  )
);

LIST @FHVHV_RAW_STAGE;

CREATE OR REPLACE TABLE T0_FHVHV_SCHEMA AS
SELECT
  'fhvhv' AS dataset,
  column_name,
  type AS column_type,
  nullable,
  expression,
  filenames,
  order_id
FROM TABLE(
  INFER_SCHEMA(
    LOCATION => '@FHVHV_RAW_STAGE',
    FILE_FORMAT => 'PARQUET_FF'
  )
);

LIST @YELLOW_RAW_STAGE;
LIST @GREEN_RAW_STAGE;
LIST @FHV_RAW_STAGE;
LIST @FHVHV_RAW_STAGE;

CREATE OR REPLACE TABLE T0_SCHEMA_ALL AS
SELECT * FROM T0_YELLOW_SCHEMA
UNION ALL
SELECT * FROM T0_GREEN_SCHEMA
UNION ALL
SELECT * FROM T0_FHV_SCHEMA
UNION ALL
SELECT * FROM T0_FHVHV_SCHEMA;

SELECT
  dataset,
  COUNT(*) AS inferred_columns
FROM T0_SCHEMA_ALL
GROUP BY dataset
ORDER BY dataset;