-- T5: Transform external data (spatial joins + event expansion)
-- Run after: t5_fetch_data.sql
-- Run before: t5_gold.sql

USE WAREHOUSE BIGDATA_MZMB_WH;
USE DATABASE BIGDATA_TAXI_MZMB;

CREATE OR REPLACE TABLE EXTERNAL_DATA.T5_SCHOOLS_BY_ZONE AS
SELECT
    tz.LOCATION_ID, tz.BOROUGH, tz.ZONE, COUNT(*) AS SCHOOL_COUNT
FROM EXTERNAL_DATA.T5_SCHOOLS_RAW s
JOIN EXTERNAL_DATA.TAXI_ZONES_GEOM tz
    ON ST_CONTAINS(tz.GEOM, ST_POINT(s.LONGITUDE, s.LATITUDE))
GROUP BY tz.LOCATION_ID, tz.BOROUGH, tz.ZONE;

CREATE OR REPLACE TABLE EXTERNAL_DATA.T5_ATTRACTIONS_BY_ZONE AS
SELECT
    tz.LOCATION_ID, tz.BOROUGH, tz.ZONE, COUNT(*) AS ATTRACTION_COUNT
FROM EXTERNAL_DATA.T5_ATTRACTIONS_RAW a
JOIN EXTERNAL_DATA.TAXI_ZONES_GEOM tz
    ON ST_CONTAINS(tz.GEOM, ST_POINT(a.LONGITUDE, a.LATITUDE))
GROUP BY tz.LOCATION_ID, tz.BOROUGH, tz.ZONE;

CREATE OR REPLACE TABLE EXTERNAL_DATA.T5_EVENTS_HOURLY AS
WITH events_parsed AS (
    SELECT
        EVENT_ID, EVENT_BOROUGH, START_DATETIME,
        COALESCE(END_DATETIME, DATEADD('hour', 3, START_DATETIME)) AS END_DATETIME
    FROM EXTERNAL_DATA.T5_EVENTS
    WHERE START_DATETIME IS NOT NULL AND EVENT_BOROUGH IS NOT NULL
),
hours_generated AS (
    SELECT e.EVENT_BOROUGH,
        DATEADD('hour', h.VALUE::INT, DATE_TRUNC('hour', e.START_DATETIME)) AS ACTIVE_HOUR
    FROM events_parsed e,
    LATERAL FLATTEN(INPUT => ARRAY_GENERATE_RANGE(0, GREATEST(DATEDIFF('hour', e.START_DATETIME, e.END_DATETIME) + 1, 1))) h
)
SELECT ACTIVE_HOUR, EVENT_BOROUGH AS BOROUGH, COUNT(*) AS ACTIVE_EVENTS
FROM hours_generated
GROUP BY ACTIVE_HOUR, EVENT_BOROUGH;
