USE WAREHOUSE BIGDATA_MZMB_WH;
USE DATABASE BIGDATA_TAXI_MZMB;

CREATE SCHEMA IF NOT EXISTS EXTERNAL_DATA;
USE SCHEMA EXTERNAL_DATA;

CREATE OR REPLACE FILE FORMAT CSV_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL', 'null');

CREATE OR REPLACE STAGE T5_EXTERNAL_STAGE
  FILE_FORMAT = CSV_FF;

CREATE OR REPLACE TABLE EXTERNAL_DATA.TAXI_ZONE_LOOKUP (
  location_id NUMBER,
  borough STRING,
  zone STRING,
  service_zone STRING
);

COPY INTO EXTERNAL_DATA.TAXI_ZONE_LOOKUP
FROM @EXTERNAL_DATA.T5_EXTERNAL_STAGE/taxi_zone_lookup.csv
FILE_FORMAT = EXTERNAL_DATA.CSV_FF
ON_ERROR = 'CONTINUE';

SELECT *
FROM EXTERNAL_DATA.TAXI_ZONE_LOOKUP
ORDER BY location_id
LIMIT 20;



CREATE OR REPLACE TABLE EXTERNAL_DATA.TAXI_ZONES_GEOM_RAW (
  location_id NUMBER,
  borough STRING,
  zone STRING,
  wkt STRING
);

COPY INTO EXTERNAL_DATA.TAXI_ZONES_GEOM_RAW
FROM @EXTERNAL_DATA.T5_EXTERNAL_STAGE/taxi_zones_wkt.csv
FILE_FORMAT = EXTERNAL_DATA.CSV_FF
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE EXTERNAL_DATA.TAXI_ZONES_GEOM AS
SELECT
  location_id,
  borough,
  zone,
  ST_GEOGFROMWKT(wkt) AS geom
FROM EXTERNAL_DATA.TAXI_ZONES_GEOM_RAW;

CREATE OR REPLACE TABLE EXTERNAL_DATA.TAXI_ZONES AS
SELECT
  l.location_id,
  l.borough,
  l.zone,
  l.service_zone,
  g.geom
FROM EXTERNAL_DATA.TAXI_ZONE_LOOKUP l
LEFT JOIN EXTERNAL_DATA.TAXI_ZONES_GEOM g
  ON l.location_id = g.location_id;

SELECT
  location_id,
  borough,
  zone,
  service_zone,
  ST_AREA(geom) AS areaBIGDATA_TAXI_MZMB.EXTERNAL_DATABIGDATA_TAXI_MZMB.EXTERNAL_DATA
FROM EXTERNAL_DATA.TAXI_ZONES
ORDER BY location_id
LIMIT 20;