-- T5 GOLD: Enriched trip tables (one per taxi type)
-- Each table = full trip data + weather, events, schools, attractions
-- Run after: t5_fetch_data.sql and t5.sql
-- NOTE: requires LARGE warehouse (temporarily scale up before running)

ALTER WAREHOUSE BIGDATA_MZMB_WH SET WAREHOUSE_SIZE = 'LARGE';
USE WAREHOUSE BIGDATA_MZMB_WH;
USE DATABASE BIGDATA_TAXI_MZMB;

CREATE OR REPLACE TABLE GOLD.T5_YELLOW AS
SELECT
    y.*,
    tz.BOROUGH,
    tz.ZONE,
    tz.SERVICE_ZONE,
    w.TEMP_MAX_C,
    w.TEMP_MIN_C,
    w.PRECIPITATION_MM,
    COALESCE(s.SCHOOL_COUNT, 0) AS SCHOOL_COUNT,
    COALESCE(a.ATTRACTION_COUNT, 0) AS ATTRACTION_COUNT,
    COALESCE(e.ACTIVE_EVENTS, 0) AS ACTIVE_EVENTS
FROM SILVER.YELLOW_TRIPS_CLEAN y
LEFT JOIN EXTERNAL_DATA.TAXI_ZONE_LOOKUP tz ON y.PU_LOCATION_ID = tz.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_WEATHER w ON TO_DATE(y.PICKUP_DATETIME) = TO_DATE(w.DATE)
LEFT JOIN EXTERNAL_DATA.T5_SCHOOLS_BY_ZONE s ON y.PU_LOCATION_ID = s.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_ATTRACTIONS_BY_ZONE a ON y.PU_LOCATION_ID = a.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_EVENTS_HOURLY e
    ON DATE_TRUNC('hour', y.PICKUP_DATETIME) = e.ACTIVE_HOUR
    AND tz.BOROUGH = e.BOROUGH;

CREATE OR REPLACE TABLE GOLD.T5_GREEN AS
SELECT
    g.*,
    tz.BOROUGH,
    tz.ZONE,
    tz.SERVICE_ZONE,
    w.TEMP_MAX_C,
    w.TEMP_MIN_C,
    w.PRECIPITATION_MM,
    COALESCE(s.SCHOOL_COUNT, 0) AS SCHOOL_COUNT,
    COALESCE(a.ATTRACTION_COUNT, 0) AS ATTRACTION_COUNT,
    COALESCE(e.ACTIVE_EVENTS, 0) AS ACTIVE_EVENTS
FROM SILVER.GREEN_TRIPS_CLEAN g
LEFT JOIN EXTERNAL_DATA.TAXI_ZONE_LOOKUP tz ON g.PU_LOCATION_ID = tz.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_WEATHER w ON TO_DATE(g.PICKUP_DATETIME) = TO_DATE(w.DATE)
LEFT JOIN EXTERNAL_DATA.T5_SCHOOLS_BY_ZONE s ON g.PU_LOCATION_ID = s.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_ATTRACTIONS_BY_ZONE a ON g.PU_LOCATION_ID = a.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_EVENTS_HOURLY e
    ON DATE_TRUNC('hour', g.PICKUP_DATETIME) = e.ACTIVE_HOUR
    AND tz.BOROUGH = e.BOROUGH;

CREATE OR REPLACE TABLE GOLD.T5_FHV AS
SELECT
    f.*,
    tz.BOROUGH,
    tz.ZONE,
    tz.SERVICE_ZONE,
    w.TEMP_MAX_C,
    w.TEMP_MIN_C,
    w.PRECIPITATION_MM,
    COALESCE(s.SCHOOL_COUNT, 0) AS SCHOOL_COUNT,
    COALESCE(a.ATTRACTION_COUNT, 0) AS ATTRACTION_COUNT,
    COALESCE(e.ACTIVE_EVENTS, 0) AS ACTIVE_EVENTS
FROM SILVER.FHV_TRIPS_CLEAN f
LEFT JOIN EXTERNAL_DATA.TAXI_ZONE_LOOKUP tz ON f.PU_LOCATION_ID = tz.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_WEATHER w ON TO_DATE(f.PICKUP_DATETIME) = TO_DATE(w.DATE)
LEFT JOIN EXTERNAL_DATA.T5_SCHOOLS_BY_ZONE s ON f.PU_LOCATION_ID = s.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_ATTRACTIONS_BY_ZONE a ON f.PU_LOCATION_ID = a.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_EVENTS_HOURLY e
    ON DATE_TRUNC('hour', f.PICKUP_DATETIME) = e.ACTIVE_HOUR
    AND tz.BOROUGH = e.BOROUGH;

CREATE OR REPLACE TABLE GOLD.T5_FHVHV AS
SELECT
    f.*,
    tz.BOROUGH,
    tz.ZONE,
    tz.SERVICE_ZONE,
    w.TEMP_MAX_C,
    w.TEMP_MIN_C,
    w.PRECIPITATION_MM,
    COALESCE(s.SCHOOL_COUNT, 0) AS SCHOOL_COUNT,
    COALESCE(a.ATTRACTION_COUNT, 0) AS ATTRACTION_COUNT,
    COALESCE(e.ACTIVE_EVENTS, 0) AS ACTIVE_EVENTS
FROM SILVER.FHVHV_TRIPS_CLEAN f
LEFT JOIN EXTERNAL_DATA.TAXI_ZONE_LOOKUP tz ON f.PU_LOCATION_ID = tz.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_WEATHER w ON TO_DATE(f.PICKUP_DATETIME) = TO_DATE(w.DATE)
LEFT JOIN EXTERNAL_DATA.T5_SCHOOLS_BY_ZONE s ON f.PU_LOCATION_ID = s.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_ATTRACTIONS_BY_ZONE a ON f.PU_LOCATION_ID = a.LOCATION_ID
LEFT JOIN EXTERNAL_DATA.T5_EVENTS_HOURLY e
    ON DATE_TRUNC('hour', f.PICKUP_DATETIME) = e.ACTIVE_HOUR
    AND tz.BOROUGH = e.BOROUGH;

ALTER WAREHOUSE BIGDATA_MZMB_WH SET WAREHOUSE_SIZE = 'XSMALL';
