USE WAREHOUSE BIGDATA_MZMB_WH;

CREATE SCHEMA IF NOT EXISTS BIGDATA_TAXI_MZMB.BRONZE;
CREATE SCHEMA IF NOT EXISTS BIGDATA_TAXI_MZMB.SILVER;
CREATE SCHEMA IF NOT EXISTS BIGDATA_TAXI_MZMB.GOLD;

USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT parquet_ff
  TYPE = PARQUET;

CREATE OR REPLACE STAGE tlc_stage
  FILE_FORMAT = parquet_ff;

LIST @tlc_stage;