-- T8: FHVHV impact on yellow/green taxi services
-- Analyzes how Uber/Lyft emergence influenced traditional taxis and smaller competitors

USE WAREHOUSE BIGDATA_MZMB_WH;
USE DATABASE BIGDATA_TAXI_MZMB;

CREATE OR REPLACE TABLE GOLD.T8_MONTHLY_MARKET_SHARE AS
WITH monthly AS (
    SELECT PICKUP_YEAR, PICKUP_MONTH, COUNT(*) AS TRIP_COUNT, 'yellow' AS DATASET
    FROM SILVER.YELLOW_TRIPS_CLEAN GROUP BY PICKUP_YEAR, PICKUP_MONTH
    UNION ALL
    SELECT PICKUP_YEAR, PICKUP_MONTH, COUNT(*), 'green'
    FROM SILVER.GREEN_TRIPS_CLEAN GROUP BY PICKUP_YEAR, PICKUP_MONTH
    UNION ALL
    SELECT PICKUP_YEAR, PICKUP_MONTH, COUNT(*), 'fhv'
    FROM SILVER.FHV_TRIPS_CLEAN GROUP BY PICKUP_YEAR, PICKUP_MONTH
    UNION ALL
    SELECT PICKUP_YEAR, PICKUP_MONTH, COUNT(*), 'uber'
    FROM SILVER.FHVHV_TRIPS_CLEAN WHERE HVFHS_LICENSE_NUM = 'HV0003'
    GROUP BY PICKUP_YEAR, PICKUP_MONTH
    UNION ALL
    SELECT PICKUP_YEAR, PICKUP_MONTH, COUNT(*), 'lyft'
    FROM SILVER.FHVHV_TRIPS_CLEAN WHERE HVFHS_LICENSE_NUM = 'HV0005'
    GROUP BY PICKUP_YEAR, PICKUP_MONTH
    UNION ALL
    SELECT PICKUP_YEAR, PICKUP_MONTH, COUNT(*), 'via'
    FROM SILVER.FHVHV_TRIPS_CLEAN WHERE HVFHS_LICENSE_NUM = 'HV0004'
    GROUP BY PICKUP_YEAR, PICKUP_MONTH
    UNION ALL
    SELECT PICKUP_YEAR, PICKUP_MONTH, COUNT(*), 'juno'
    FROM SILVER.FHVHV_TRIPS_CLEAN WHERE HVFHS_LICENSE_NUM = 'HV0002'
    GROUP BY PICKUP_YEAR, PICKUP_MONTH
),
totals AS (
    SELECT PICKUP_YEAR, PICKUP_MONTH, SUM(TRIP_COUNT) AS TOTAL_TRIPS
    FROM monthly GROUP BY PICKUP_YEAR, PICKUP_MONTH
)
SELECT
    m.PICKUP_YEAR,
    m.PICKUP_MONTH,
    DATE_FROM_PARTS(m.PICKUP_YEAR, m.PICKUP_MONTH, 1) AS MONTH_DATE,
    m.DATASET,
    m.TRIP_COUNT,
    t.TOTAL_TRIPS,
    ROUND(m.TRIP_COUNT * 100.0 / t.TOTAL_TRIPS, 2) AS MARKET_SHARE_PCT
FROM monthly m
JOIN totals t ON m.PICKUP_YEAR = t.PICKUP_YEAR AND m.PICKUP_MONTH = t.PICKUP_MONTH
ORDER BY m.PICKUP_YEAR, m.PICKUP_MONTH, m.DATASET;

CREATE OR REPLACE TABLE GOLD.T8_YEARLY_COMPARISON AS
SELECT
    PICKUP_YEAR,
    DATASET,
    SUM(TRIP_COUNT) AS ANNUAL_TRIPS,
    ROUND(SUM(TRIP_COUNT) * 100.0 / SUM(TOTAL_TRIPS), 2) AS ANNUAL_MARKET_SHARE_PCT
FROM GOLD.T8_MONTHLY_MARKET_SHARE
GROUP BY PICKUP_YEAR, DATASET
ORDER BY PICKUP_YEAR, DATASET;

CREATE OR REPLACE TABLE GOLD.T8_YOY_GROWTH AS
WITH yearly AS (
    SELECT PICKUP_YEAR, DATASET, SUM(TRIP_COUNT) AS ANNUAL_TRIPS
    FROM GOLD.T8_MONTHLY_MARKET_SHARE
    GROUP BY PICKUP_YEAR, DATASET
)
SELECT
    y.PICKUP_YEAR,
    y.DATASET,
    y.ANNUAL_TRIPS,
    LAG(y.ANNUAL_TRIPS) OVER (PARTITION BY y.DATASET ORDER BY y.PICKUP_YEAR) AS PREV_YEAR_TRIPS,
    ROUND((y.ANNUAL_TRIPS - LAG(y.ANNUAL_TRIPS) OVER (PARTITION BY y.DATASET ORDER BY y.PICKUP_YEAR))
        * 100.0 / NULLIF(LAG(y.ANNUAL_TRIPS) OVER (PARTITION BY y.DATASET ORDER BY y.PICKUP_YEAR), 0), 2) AS YOY_GROWTH_PCT
FROM yearly y
ORDER BY y.DATASET, y.PICKUP_YEAR;

CREATE OR REPLACE TABLE GOLD.T8_PRE_POST_FHVHV AS
WITH pre AS (
    SELECT DATASET, ROUND(AVG(TRIP_COUNT), 0) AS AVG_MONTHLY_TRIPS
    FROM GOLD.T8_MONTHLY_MARKET_SHARE
    WHERE PICKUP_YEAR BETWEEN 2015 AND 2018
    GROUP BY DATASET
),
post AS (
    SELECT DATASET, ROUND(AVG(TRIP_COUNT), 0) AS AVG_MONTHLY_TRIPS
    FROM GOLD.T8_MONTHLY_MARKET_SHARE
    WHERE PICKUP_YEAR BETWEEN 2021 AND 2024
    GROUP BY DATASET
)
SELECT
    COALESCE(pre.DATASET, post.DATASET) AS DATASET,
    pre.AVG_MONTHLY_TRIPS AS PRE_FHVHV_AVG_MONTHLY,
    post.AVG_MONTHLY_TRIPS AS POST_FHVHV_AVG_MONTHLY,
    ROUND((post.AVG_MONTHLY_TRIPS - pre.AVG_MONTHLY_TRIPS) * 100.0 / NULLIF(pre.AVG_MONTHLY_TRIPS, 0), 2) AS PCT_CHANGE
FROM pre
FULL OUTER JOIN post ON pre.DATASET = post.DATASET
ORDER BY DATASET;
